spring.application.name=ged-app-backend

# URL de connexion
spring.datasource.url=jdbc:postgresql://localhost:5432/ged-app-bd
# Identifiants
spring.datasource.username=postgres
spring.datasource.password=1234
# Driver (optionnel dans les versions récentes)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' met à jour la structure, 'create-drop' recrée à chaque lancement
spring.jpa.hibernate.ddl-auto=validate
# Affiche les requêtes SQL dans la console (optionnel)
spring.jpa.show-sql=true

